### ISSUE TITLE
unavailable

### ISSUE THREAD

**Issue by pandatest2023** [t9t/gomft#2]
go run .\gomft.go
bug info
# github.com/t9t/gomft/mft
E:\go\src\github.com\t9t\gomft\mft\mft.go:407:24: syntax error: unexpected b10000000, expecting {
E:\go\src\github.com\t9t\gomft\mft\mft.go:408:3: syntax error: unexpected for, expecting expression
E:\go\src\github.com\t9t\gomft\mft\mft.go:412:2: syntax error: non-declaration statement outside function body

**Comment by t9t** [comment]
Hi @jonytest, thanks for reaching out. That is odd. The build status in Travis is green, and I haven't made any changes since. When I build it on my machine I get no such issues.

It looks like an issue with this line:

```
if data[len(data)-1]&0b10000000 == 0b10000000 {
```

Somehow it cannot interpret the `0b10000000` constant, and I believe the other errors follow from that. This looks related: https://www.infoworld.com/article/3408740/golang-113-adds-number-literal-prefixes.html

What is the output of `go version`? I have only tested it with go 1.13 so far, so perhaps I should document that in the readme.
